import { PUBLIC_BACKEND_BASE_URL, PUBLIC_GOOGLE_CLIENT_ID } from '$env/static/public';

export const BACKEND_BASE_URL = PUBLIC_BACKEND_BASE_URL ?? '';
export const GOOGLE_CLIENT_ID = PUBLIC_GOOGLE_CLIENT_ID ?? '';
